version: '3.8'

services:
  dup_dep_service:
    build:
      context: ./app  # Path to your agent service
    ports:
      - "8000:8000"
    container_name: hap_dup_det_service
    extra_hosts:
      - "host.docker.internal:host-gateway"
    env_file:
      - .env  # or ./config/agent.env
    volumes:
      - ./app:/app  # Use relative path to project folder